name: Push Workflow

on: push

jobs:
  build:
    timeout-minutes: 10
    runs-on: [self-hosted, ubuntu-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: 'temurin'

      - name: Maven tests
        run: mvn clean test
        
      - name: Maven Build
        run: mvn -Dmaven.test.skip=true clean verify -U